package com.joaovicttors.domain.entities

data class Anime(
    val id: Int,
    val aniListId: Int?,
    val malId: Int?,
    val tmdbId: Int?,
    val format: Int?,
    val status: Int?,
    val titles: Map<String, String>?,
    val descriptions: Map<String, String>?,
    val startDate: String?,
    val endDate: String?,
    val weeklyAiringDay: Int?,
    val seasonPeriod: Int?,
    val seasonYear: Int?,
    val episodesCount: Int?,
    val episodeDuration: Int?,
    val trailerUrl: String?,
    val coverImage: String?,
    val hasCoverImage: Boolean?,
    val coverColor: String?,
    val bannerImage: String?,
    val genres: List<String>?,
    val sequel: Int?,
    val prequel: Int?,
    val score: Float?,
    val nsfw: Boolean?,
    val recommendations: List<Int>?
)
